services:
  - type: web
    name: dhruv-portfolio
    runtime: static
    repo: https://github.com/dptel22/portfolio-website
    branch: main
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /portfolio/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: redirect
        source: /Resume.pdf
        destination: /resume.pdf
